site_name: Administração de TI
nav:
  - Home: index.md
  - Sobre: about.md
  - Introdução: intro.md
  - GLPI: glpi.md
  - MKDocs: mkdocs.md
  - Conclusão: conclusao.md

plugins:
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
